// SkyCore How-To Hub manifest.
// Add new entries at the TOP (array is newest-first).
// The scheduled generator appends here — see scripts/generate_howto.py
window.SKYCORE_HOWTO = [
  {
    slug: "vmware-migration-azure-guide-smbs",
    title: "Your Comprehensive VMware Migration to Azure Guide: A SkyCore Solutions Blueprint for SMBs",
    date: "2026-06-21",
    readTime: "25 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "3-5 hours (excluding data transfer time)",
    keyword: "VMware migration to Azure guide",
    excerpt: "Migrating your on-premises VMware virtual machines to Azure can unlock significant cost savings and agility for your SMB. This VMware migration to Azure guide provides a step-by-step blueprint for a successful agentless transition.",
    image: "https://images.pexels.com/photos/6536941/pexels-photo-6536941.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "office-365-mfa-setup-guide",
    title: "Comprehensive Office 365 MFA Setup Guide for Enhanced Security",
    date: "2026-06-19",
    readTime: "15 min read",
    category: "Security Hardening",
    difficulty: "Intermediate",
    timeEstimate: "1-2 hours",
    keyword: "Office 365 MFA setup guide",
    excerpt: "Secure your Microsoft 365 accounts with this comprehensive Office 365 MFA setup guide. Implement robust multi-factor authentication to protect against unauthorized access.",
    image: "https://images.pexels.com/photos/39584/censorship-limitations-freedom-of-expression-restricted-39584.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "azure-functions-serverless-deployment-guide-smb",
    title: "Azure Functions Serverless Deployment Guide for SMBs | SkyCore Solutions",
    date: "2026-06-17",
    readTime: "15 min read",
    category: "Infrastructure Revamp",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours",
    keyword: "Azure Functions serverless deployment guide",
    excerpt: "SkyCore Solutions presents a comprehensive Azure Functions serverless deployment guide tailored for small and medium businesses. Learn to deploy cost-effective, event-driven applications on Azure.",
    image: "https://images.pexels.com/photos/16764815/pexels-photo-16764815.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "migrate-file-server-azure-files-smb-guide",
    title: "SkyCore Solutions Guide: How to Migrate Your File Server to Azure Files with Azure File Sync",
    date: "2026-06-13",
    readTime: "25 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours (initial setup), plus data synchronization time",
    keyword: "migrate file server to Azure Files guide",
    excerpt: "This authoritative guide helps SMBs migrate file server to Azure Files, leveraging Azure File Sync for a hybrid approach that enhances security and performance while maintaining local access.",
    image: "https://images.pexels.com/photos/19825057/pexels-photo-19825057.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "windows-server-hardening-checklist",
    title: "The Definitive Windows Server Hardening Checklist for 2026",
    date: "2026-06-13",
    readTime: "18 min read",
    category: "Security Hardening",
    difficulty: "Advanced",
    timeEstimate: "3-5 hours (initial implementation)",
    keyword: "Windows Server hardening checklist",
    excerpt: "This guide provides a comprehensive Windows Server hardening checklist, offering actionable, CLI-first steps to secure your critical infrastructure against evolving threats. Master foundational security, privileged access, and advanced threat protection.",
    image: "https://images.pexels.com/photos/37730211/pexels-photo-37730211.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "office-365-migration-step-by-step",
    title: "Office 365 Migration Step by Step: A Comprehensive Guide for IT Professionals",
    date: "2026-06-10",
    readTime: "25 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "4-6 hours",
    keyword: "Office 365 migration step by step",
    excerpt: "Ready for an Office 365 migration step by step? This guide ensures a smooth transition for your organization's email and collaboration services.",
    image: "https://images.pexels.com/photos/28751189/pexels-photo-28751189.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "server-hardening-checklist-azure-windows",
    title: "The Definitive Server Hardening Checklist for Azure and Windows Environments",
    date: "2026-06-07",
    readTime: "12 min read",
    category: "Security Hardening",
    difficulty: "Advanced",
    timeEstimate: "3-5 hours",
    keyword: "server hardening checklist",
    excerpt: "Implement SkyCore's expert server hardening checklist to fortify your Windows Server and Azure virtual machines against modern threats. This guide provides actionable, CLI-first steps for enhanced security.",
    image: "https://images.pexels.com/photos/17323801/pexels-photo-17323801.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "azure-virtual-desktop-setup-guide-smb",
    title: "Mastering Azure Virtual Desktop: A Comprehensive Setup Guide for SMBs",
    date: "2026-06-05",
    readTime: "14 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours",
    keyword: "Azure Virtual Desktop setup guide",
    excerpt: "This comprehensive Azure Virtual Desktop setup guide by SkyCore Solutions empowers SMBs to deploy a robust, secure, and scalable virtual desktop infrastructure. Enhance productivity and reduce IT overhead with AVD.",
    image: "https://images.pexels.com/photos/5473298/pexels-photo-5473298.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "implement-zero-trust-security",
    title: "How to Implement Zero Trust Security: A SkyCore Solutions Guide",
    date: "2026-06-04",
    readTime: "18 min read",
    category: "Security Hardening",
    difficulty: "Advanced",
    timeEstimate: "3-5 hours (initial setup), ongoing",
    keyword: "how to implement zero trust security",
    excerpt: "Implementing Zero Trust security is no longer optional; it's a strategic imperative for modern enterprises. This guide provides actionable steps, leveraging Azure services and NIST/CISA best practices, to transition your organization to a 'never trust, always verify' model.",
    image: "https://images.pexels.com/photos/35908540/pexels-photo-35908540.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "migrate-sharepoint-to-sharepoint-online-guide-smb",
    title: "Seamlessly Migrate SharePoint to SharePoint Online: An SMB Guide with SPMT",
    date: "2026-06-01",
    readTime: "18 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "1-2 weeks (planning, pilot, full execution)",
    keyword: "migrate SharePoint to SharePoint Online",
    excerpt: "Unlock modern collaboration by migrating your on-premises SharePoint to SharePoint Online. This guide details using the SharePoint Migration Tool (SPMT) for SMBs.",
    image: "https://images.pexels.com/photos/6481663/pexels-photo-6481663.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "docker-containerization-essential-guide",
    title: "Mastering Docker Containerization: A SkyCore Solutions How-To Guide",
    date: "2026-06-01",
    readTime: "18 min read",
    category: "Infrastructure Revamp",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours",
    keyword: "Docker containerization tutorial",
    excerpt: "This guide provides a comprehensive Docker containerization tutorial, demonstrating how to build, run, and orchestrate applications using Docker and Docker Compose. Leverage containerization for streamlined development and deployment workflows.",
    image: "https://images.pexels.com/photos/37730212/pexels-photo-37730212.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "secure-small-business-endpoint-protection",
    title: "Comprehensive Guide: Endpoint Protection for Small Business with Microsoft Defender",
    date: "2026-05-31",
    readTime: "18 min read",
    category: "Security Hardening",
    difficulty: "Intermediate",
    timeEstimate: "3-5 hours",
    keyword: "endpoint protection for small business",
    excerpt: "Securing your small business's endpoints is critical against modern cyber threats. This guide outlines how to deploy and manage robust endpoint protection using Microsoft Defender for Business effectively.",
    image: "https://images.pexels.com/photos/5935794/pexels-photo-5935794.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "microsoft-365-tenant-to-tenant-migration-smb-guide",
    title: "Seamless Microsoft 365 Tenant to Tenant Migration for SMBs: An Implementation Guide",
    date: "2026-05-30",
    readTime: "20 min read",
    category: "Cloud Migration",
    difficulty: "Intermediate",
    timeEstimate: "3-5 business days for planning and preparation; migration window highly variable.",
    keyword: "Microsoft 365 tenant to tenant migration",
    excerpt: "Planning a Microsoft 365 tenant to tenant migration? This guide helps SMBs navigate the complexities of moving users, mailboxes, and data between Microsoft 365 tenants.",
    image: "https://images.pexels.com/photos/33233646/pexels-photo-33233646.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "microsoft-entra-privileged-identity-management-guide",
    title: "Mastering Microsoft Entra Privileged Identity Management: A SkyCore Implementation Guide for SMBs",
    date: "2026-05-30",
    readTime: "15 min read",
    category: "Infrastructure Revamp",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours (initial setup), ongoing management",
    keyword: "Microsoft Entra Privileged Identity Management",
    excerpt: "This comprehensive guide from SkyCore Solutions walks SMBs through implementing Microsoft Entra Privileged Identity Management (PIM) to secure critical access. Learn how to enable Just-In-Time administration and strengthen your cloud security posture.",
    image: "https://images.pexels.com/photos/2882630/pexels-photo-2882630.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "ransomware-protection-small-business-skycore",
    title: "Comprehensive Ransomware Protection for Small Business: A SkyCore Guide",
    date: "2026-05-28",
    readTime: "15 min read",
    category: "Security Hardening",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours (initial setup), ongoing",
    keyword: "ransomware protection for small business",
    excerpt: "Ransomware remains a top threat for small businesses. This guide provides actionable steps to implement robust ransomware protection, ensuring business continuity.",
    image: "https://images.pexels.com/photos/5475752/pexels-photo-5475752.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "it-disaster-recovery-guide-azure",
    title: "The SkyCore IT Disaster Recovery Guide: Building Resilient Azure Architectures",
    date: "2026-05-25",
    readTime: "18 min read",
    category: "IT Strategy",
    difficulty: "Advanced",
    timeEstimate: "2-3 hours (initial setup & planning)",
    keyword: "IT disaster recovery guide",
    excerpt: "Disruptions are inevitable. This guide provides a strategic IT disaster recovery framework, leveraging Azure's robust BCDR services and industry best practices to safeguard your operations.",
    image: "https://images.pexels.com/photos/17489163/pexels-photo-17489163.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "zero-trust-network-access-implementation-guide",
    title: "Mastering Zero Trust Network Access Implementation: A SkyCore Solutions Guide",
    date: "2026-05-22",
    readTime: "12 min read",
    category: "Security Hardening",
    difficulty: "Advanced",
    timeEstimate: "4-8 hours (initial setup), ongoing",
    keyword: "zero trust network access implementation",
    excerpt: "This comprehensive guide from SkyCore Solutions details the steps for implementing Zero Trust Network Access, focusing on identity, device, and application security. Elevate your organization's security posture by adopting a 'never trust, always verify' approach.",
    image: "https://images.pexels.com/photos/39624/padlock-lock-chain-key-39624.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
  {
    slug: "disaster-recovery-plan-small-business-azure",
    title: "Building a Robust Disaster Recovery Plan for Small Business with Azure",
    date: "2026-05-20",
    readTime: "18 min read",
    category: "IT Strategy",
    difficulty: "Intermediate",
    timeEstimate: "2-3 hours (initial setup) + ongoing",
    keyword: "disaster recovery plan for small business",
    excerpt: "A well-crafted disaster recovery plan is crucial for small businesses to withstand outages. This guide provides actionable steps to leverage Azure for resilience.",
    image: "https://images.pexels.com/photos/2827756/pexels-photo-2827756.jpeg?auto=compress&cs=tinysrgb&w=800&fit=crop&h=450"
  },
];
